### ISSUE TITLE
Unable to include the library following the steps in the documentation

### ISSUE THREAD

**Issue by edu-zamora** [Kennyc1012/SnackBar#3]
After adding to my `build.gralde` the next:

    repositories {
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        mavenCentral()
    }

    dependencies {
        compile 'com.github.kennyc1012:snackbar:1.0.1-SNAPSHOT:api11Release@aar'
    }

When I try to sync the changes in the gradle files, I get the next error:

    Error: Failed to find: com.github.kennyc1012:snackbar:1.0.1-SNAPSHOT

**Comment by Kennyc1012** [comment]
Closing as no response was ever given.
