### ISSUE TITLE
Way to determine if Action button wasn't pressed?

### ISSUE THREAD

**Issue by JoelReeves** [Kennyc1012/SnackBar#6]
I was wondering if there's a way to determine if the Action button wasn't pressed when the SnackBar is dismissed?

I can see you have a setSnackBarListener method but I don't see a way to tell if the action button wasn't pressed.

**Comment by Kennyc1012** [comment]
No, it could be added to the onSnackBarFinished callback, but then I would think the need for the onSnackBarAction could be removed as well. I don't think there needs to be both, as you should anticipate the action clicked rather than the action not clicked

**Comment by JoelReeves** [comment]
Yeah I understand. In the app I'm developing I want want action to happen if the action button is pressed, and another to happen if the Snackbar is dismissed and the button wasn't pressed.

**Comment by Kennyc1012** [comment]
Thinking about this more, I like the idea as it removes having two click events for the action. I will add this.

**Comment by Kennyc1012** [comment]
Release in 2.3

**Comment by JoelReeves** [comment]
Wow. thanks for the fast turnaround!
