### ISSUE TITLE
Action message color always yellow?

### ISSUE THREAD

**Issue by JoelReeves** [Kennyc1012/SnackBar#7]
Just to be sure I tried using in a new project with simply:

     new SnackBarItem.Builder(this)
                .setMessage("Test SnackBar")
                .setActionMessage("Test")
                .setActionMessageColorResource(R.color.white)
                .show();

And the Action Message font was yellow. Even if I used the .setActionMessageColor or .setActionMessageColorResource methods the color would stay yellow.

My R.color.white is defined as being #FFFFFF

**Comment by JoelReeves** [comment]
Maybe never mind. I tried a different shade of white and it seemed to work. (#F5F5F5). Strange that the first white gave the text a yellowish color

**Comment by Kennyc1012** [comment]
I think I know the reason, the default values of the colors are set to -1 and tested against that, and white will translate to -1. If the value is -1, it will default back to yellow.

**Comment by JoelReeves** [comment]
That's just for the action message text or is it also the message text?

**Comment by Kennyc1012** [comment]
Its for both, it has been fixed in 2.4 release. The default values will be transparent (which obviously won't show) so white or any color, asides from transparent, will now work.
